## Be sure path is writable
backup_path : '/home/siduser<ID>/ansible-pan-labs/'
## Set to true to backup config
backup_configuration: 'true'
## Insert name of backup file to restore. If blank no restoration will occur
## For restore ensure backup_configuration = true. Config will be backed up prior to restore of file
restore_file: ''
restore_configuration: 'false'
